-- =========================================================
-- Seed manual: obras
-- Generado desde listado_obras_desplegables_completos(1).xlsx
-- style/style_id eliminado intencionadamente.
-- Requiere que collection y technique estén previamente cargadas.
-- =========================================================

INSERT INTO artwork (
    collection_id,
    technique_id,
    title,
    slug,
    year,
    description,
    observations,
    width_cm,
    height_cm,
    price,
    status,
    is_featured,
    is_visible,
    sort_order
)
VALUES
    (
        (SELECT id FROM collection WHERE slug = 'otras-obras'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'La bruja de Cadaqués',
        'la-bruja-de-cadaques',
        2020,
        NULL,
        NULL,
        65.00,
        81.00,
        580.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        1
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Nuestra Señora de la Asunción',
        'nuestra-senora-de-la-asuncion',
        2024,
        NULL,
        NULL,
        60.00,
        81.00,
        560.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        2
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Doña Casta',
        'dona-casta',
        2021,
        NULL,
        NULL,
        80.00,
        80.00,
        640.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        3
    ),
    (
        (SELECT id FROM collection WHERE slug = 'otras-obras'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Rosa rosae',
        'rosa-rosae',
        2022,
        NULL,
        NULL,
        70.00,
        70.00,
        560.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        4
    ),
    (
        (SELECT id FROM collection WHERE slug = 'otras-obras'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Nadie me abraza',
        'nadie-me-abraza',
        2021,
        NULL,
        NULL,
        92.00,
        60.00,
        600.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        5
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre tabla'),
        'Fábrica abandonada',
        'fabrica-abandonada',
        2021,
        NULL,
        NULL,
        120.00,
        80.00,
        800.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        6
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Paseo por Tetuán',
        'paseo-por-tetuan',
        2024,
        NULL,
        NULL,
        60.00,
        81.00,
        560.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        7
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Joven melómano',
        'joven-melomano',
        2020,
        NULL,
        NULL,
        73.00,
        60.00,
        NULL,
        'PRIVATE_COLLECTION'::artwork_status,
        FALSE,
        TRUE,
        8
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Ione',
        'ione',
        2021,
        NULL,
        NULL,
        80.00,
        100.00,
        NULL,
        'PRIVATE_COLLECTION'::artwork_status,
        FALSE,
        TRUE,
        9
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Cara oculta en Plaza San Marcos',
        'cara-oculta-en-plaza-san-marcos',
        2020,
        NULL,
        NULL,
        65.00,
        81.00,
        580.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        10
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Isabelle',
        'isabelle-2022',
        2022,
        NULL,
        NULL,
        50.00,
        50.00,
        400.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        11
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Efímera modernidad',
        'efimera-modernidad',
        2021,
        NULL,
        NULL,
        100.00,
        100.00,
        800.00,
        'SOLD'::artwork_status,
        FALSE,
        TRUE,
        12
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Basílica del Pilar',
        'basilica-del-pilar',
        2020,
        NULL,
        NULL,
        90.00,
        90.00,
        720.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        13
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre tabla'),
        'Purasal',
        'purasal',
        2021,
        NULL,
        NULL,
        80.00,
        80.00,
        640.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        14
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Desde el cuarto creciente',
        'desde-el-cuarto-creciente',
        2020,
        NULL,
        NULL,
        60.00,
        60.00,
        NULL,
        'PRIVATE_COLLECTION'::artwork_status,
        FALSE,
        TRUE,
        15
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Serenidad',
        'serenidad',
        2021,
        NULL,
        NULL,
        73.00,
        60.00,
        NULL,
        'PRIVATE_COLLECTION'::artwork_status,
        FALSE,
        TRUE,
        16
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Vigilando el abandono',
        'vigilando-el-abandono',
        2021,
        NULL,
        NULL,
        100.00,
        100.00,
        800.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        17
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre tabla'),
        'In memoriam',
        'in-memoriam',
        2021,
        NULL,
        NULL,
        80.00,
        80.00,
        640.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        18
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Patinando por el Barrio Gótico',
        'patinando-por-el-barrio-gotico',
        2023,
        NULL,
        NULL,
        73.00,
        100.00,
        580.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        19
    ),
    (
        (SELECT id FROM collection WHERE slug = 'otras-obras'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Mi primer Rembrandt',
        'mi-primer-rembrandt',
        2020,
        NULL,
        NULL,
        55.00,
        45.00,
        400.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        20
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Acrílico sobre lienzo'),
        'David',
        'david',
        2024,
        NULL,
        NULL,
        80.00,
        100.00,
        NULL,
        'PRIVATE_COLLECTION'::artwork_status,
        FALSE,
        TRUE,
        21
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Acrílico sobre lienzo'),
        'Adri',
        'adri',
        2024,
        NULL,
        NULL,
        81.00,
        100.00,
        NULL,
        'PRIVATE_COLLECTION'::artwork_status,
        FALSE,
        TRUE,
        22
    ),
    (
        (SELECT id FROM collection WHERE slug = 'ventanas-del-alma'),
        (SELECT id FROM technique WHERE name = 'Carboncillo sobre papel'),
        'Susan',
        'susan',
        2019,
        NULL,
        NULL,
        40.00,
        40.00,
        300.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        23
    ),
    (
        (SELECT id FROM collection WHERE slug = 'ventanas-del-alma'),
        (SELECT id FROM technique WHERE name = 'Carboncillo sobre papel'),
        'Bea',
        'bea',
        2019,
        NULL,
        NULL,
        40.00,
        40.00,
        300.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        24
    ),
    (
        (SELECT id FROM collection WHERE slug = 'ventanas-del-alma'),
        (SELECT id FROM technique WHERE name = 'Carboncillo sobre papel'),
        'Portobello',
        'portobello',
        2019,
        NULL,
        NULL,
        40.00,
        40.00,
        300.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        25
    ),
    (
        (SELECT id FROM collection WHERE slug = 'ventanas-del-alma'),
        (SELECT id FROM technique WHERE name = 'Carboncillo sobre papel'),
        'Smoker',
        'smoker',
        2019,
        NULL,
        NULL,
        40.00,
        40.00,
        300.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        26
    ),
    (
        (SELECT id FROM collection WHERE slug = 'ventanas-del-alma'),
        (SELECT id FROM technique WHERE name = 'Carboncillo sobre papel'),
        'Seattle',
        'seattle',
        2019,
        NULL,
        NULL,
        40.00,
        40.00,
        300.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        27
    ),
    (
        (SELECT id FROM collection WHERE slug = 'ventanas-del-alma'),
        (SELECT id FROM technique WHERE name = 'Carboncillo sobre papel'),
        'Miami',
        'miami',
        2019,
        NULL,
        NULL,
        40.00,
        40.00,
        300.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        28
    ),
    (
        (SELECT id FROM collection WHERE slug = 'ventanas-del-alma'),
        (SELECT id FROM technique WHERE name = 'Carboncillo sobre papel'),
        'Gin I',
        'gin-i',
        2019,
        NULL,
        NULL,
        40.00,
        40.00,
        300.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        29
    ),
    (
        (SELECT id FROM collection WHERE slug = 'ventanas-del-alma'),
        (SELECT id FROM technique WHERE name = 'Carboncillo sobre papel'),
        'Hands',
        'hands',
        2019,
        NULL,
        NULL,
        40.00,
        40.00,
        300.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        30
    ),
    (
        (SELECT id FROM collection WHERE slug = 'ventanas-del-alma'),
        (SELECT id FROM technique WHERE name = 'Carboncillo sobre papel'),
        'Gin II',
        'gin-ii',
        2019,
        NULL,
        NULL,
        40.00,
        40.00,
        300.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        31
    ),
    (
        (SELECT id FROM collection WHERE slug = 'ventanas-del-alma'),
        (SELECT id FROM technique WHERE name = 'Carboncillo sobre papel'),
        'Lion Queen',
        'lion-queen',
        2022,
        NULL,
        NULL,
        40.00,
        40.00,
        300.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        32
    ),
    (
        (SELECT id FROM collection WHERE slug = 'ventanas-del-alma'),
        (SELECT id FROM technique WHERE name = 'Carboncillo sobre papel'),
        'Tomas',
        'tomas',
        2019,
        NULL,
        NULL,
        40.00,
        40.00,
        300.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        33
    ),
    (
        (SELECT id FROM collection WHERE slug = 'ventanas-del-alma'),
        (SELECT id FROM technique WHERE name = 'Carboncillo sobre papel'),
        'Boxer',
        'boxer',
        2019,
        NULL,
        NULL,
        40.00,
        40.00,
        300.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        34
    ),
    (
        (SELECT id FROM collection WHERE slug = 'ventanas-del-alma'),
        (SELECT id FROM technique WHERE name = 'Carboncillo sobre papel'),
        'Isabelle',
        'isabelle-2019',
        2019,
        NULL,
        NULL,
        40.00,
        40.00,
        NULL,
        'PRIVATE_COLLECTION'::artwork_status,
        FALSE,
        TRUE,
        35
    ),
    (
        (SELECT id FROM collection WHERE slug = '20x20'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'After Painting',
        'after-painting',
        2023,
        NULL,
        NULL,
        20.00,
        20.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        36
    ),
    (
        (SELECT id FROM collection WHERE slug = '20x20'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Ana Piruleta',
        'ana-piruleta',
        2023,
        NULL,
        NULL,
        20.00,
        20.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        37
    ),
    (
        (SELECT id FROM collection WHERE slug = '20x20'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Anekke',
        'anekke',
        2024,
        NULL,
        NULL,
        20.00,
        20.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        38
    ),
    (
        (SELECT id FROM collection WHERE slug = '20x20'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Basura',
        'basura',
        2023,
        NULL,
        NULL,
        20.00,
        20.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        39
    ),
    (
        (SELECT id FROM collection WHERE slug = '20x20'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Candado',
        'candado',
        2023,
        NULL,
        NULL,
        20.00,
        20.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        40
    ),
    (
        (SELECT id FROM collection WHERE slug = '20x20'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Coke',
        'coke',
        2023,
        NULL,
        NULL,
        20.00,
        20.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        41
    ),
    (
        (SELECT id FROM collection WHERE slug = '20x20'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Joven budista',
        'joven-budista',
        2025,
        NULL,
        NULL,
        20.00,
        20.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        42
    ),
    (
        (SELECT id FROM collection WHERE slug = '20x20'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Joven guerrero',
        'joven-guerrero',
        2025,
        NULL,
        NULL,
        20.00,
        20.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        43
    ),
    (
        (SELECT id FROM collection WHERE slug = '20x20'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'La Partida',
        'la-partida',
        2022,
        NULL,
        NULL,
        20.00,
        20.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        44
    ),
    (
        (SELECT id FROM collection WHERE slug = '20x20'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Little Italy',
        'little-italy',
        2024,
        NULL,
        NULL,
        20.00,
        20.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        45
    ),
    (
        (SELECT id FROM collection WHERE slug = '20x20'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Nostalgia',
        'nostalgia',
        2022,
        NULL,
        NULL,
        20.00,
        20.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        46
    ),
    (
        (SELECT id FROM collection WHERE slug = '20x20'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'In Memoriam NYC',
        'in-memoriam-nyc',
        2024,
        NULL,
        NULL,
        20.00,
        20.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        47
    ),
    (
        (SELECT id FROM collection WHERE slug = '20x20'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'NYC',
        'nyc',
        2024,
        NULL,
        NULL,
        20.00,
        20.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        48
    ),
    (
        (SELECT id FROM collection WHERE slug = '20x20'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Second Life',
        'second-life',
        2023,
        NULL,
        NULL,
        20.00,
        20.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        49
    ),
    (
        (SELECT id FROM collection WHERE slug = '20x20'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Alma del Ebro',
        'alma-del-ebro',
        2026,
        NULL,
        NULL,
        20.00,
        20.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        50
    ),
    (
        (SELECT id FROM collection WHERE slug = '20x20'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Caixaforum',
        'caixaforum',
        2026,
        NULL,
        NULL,
        20.00,
        20.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        51
    ),
    (
        (SELECT id FROM collection WHERE slug = '20x20'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Pilar',
        'pilar',
        2026,
        NULL,
        NULL,
        20.00,
        20.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        52
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Bodas de Sangre',
        'bodas-de-sangre',
        2024,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        53
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Cambios por el cambio',
        'cambios-por-el-cambio',
        2024,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        54
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Ciclon',
        'ciclon',
        2024,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        55
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Daño colateral',
        'dano-colateral',
        2024,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        56
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Destino La Costa',
        'destino-la-costa',
        2024,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        57
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Duelo',
        'duelo',
        2024,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        58
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'El drama de las vacunas',
        'el-drama-de-las-vacunas',
        2024,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        59
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Escapando a Lesbos',
        'escapando-a-lesbos',
        2024,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        60
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Escuelas para escapar',
        'escuelas-para-escapar',
        2024,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        61
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Guerra y escuela',
        'guerra-y-escuela',
        2025,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        62
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Guerreras del agua',
        'guerreras-del-agua',
        2024,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        63
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Lo consegui',
        'lo-consegui',
        2024,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        64
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Minas',
        'minas',
        2025,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        65
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Niños mineros',
        'ninos-mineros',
        2024,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        66
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Niños soldados',
        'ninos-soldados',
        2024,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        67
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Penurias en Yida',
        'penurias-en-yida',
        2024,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        68
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Resiliencia',
        'resiliencia',
        2024,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        69
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Rostros robados',
        'rostros-robados',
        2024,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        70
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Tengo hambre',
        'tengo-hambre',
        2025,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        71
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Todos somos Mahsa',
        'todos-somos-mahsa',
        2024,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        72
    ),
    (
        (SELECT id FROM collection WHERE slug = 'un-cuadro-una-historia'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Yo también quiero',
        'yo-tambien-quiero',
        2025,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'NOT_FOR_SALE'::artwork_status,
        FALSE,
        TRUE,
        73
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Rosalia',
        'rosalia',
        2020,
        NULL,
        NULL,
        60.00,
        60.00,
        400.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        74
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Amy',
        'amy',
        2020,
        NULL,
        NULL,
        60.00,
        60.00,
        400.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        75
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Bowie',
        'bowie',
        2020,
        NULL,
        NULL,
        60.00,
        60.00,
        400.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        76
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Cooper',
        'cooper',
        2019,
        NULL,
        NULL,
        60.00,
        60.00,
        400.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        77
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Bunbury',
        'bunbury',
        2019,
        NULL,
        NULL,
        60.00,
        60.00,
        NULL,
        'SOLD'::artwork_status,
        FALSE,
        TRUE,
        78
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Freddie',
        'freddie',
        2020,
        NULL,
        NULL,
        60.00,
        60.00,
        400.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        79
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'LadyGaga',
        'ladygaga',
        2019,
        NULL,
        NULL,
        60.00,
        60.00,
        400.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        80
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Lennon',
        'lennon',
        2020,
        NULL,
        NULL,
        60.00,
        60.00,
        400.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        81
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Madonna',
        'madonna',
        2020,
        NULL,
        NULL,
        60.00,
        60.00,
        400.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        82
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Michael',
        'michael',
        2020,
        NULL,
        NULL,
        60.00,
        60.00,
        400.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        83
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Prince',
        'prince',
        2019,
        NULL,
        NULL,
        60.00,
        60.00,
        400.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        84
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Acrílico sobre lienzo'),
        'Rosalia II',
        'rosalia-ii',
        2023,
        NULL,
        NULL,
        60.00,
        60.00,
        350.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        85
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Acrílico sobre lienzo'),
        'Amaral',
        'amaral',
        2024,
        NULL,
        NULL,
        60.00,
        81.00,
        350.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        86
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Acrílico sobre lienzo'),
        'Bowie II',
        'bowie-ii',
        2024,
        NULL,
        NULL,
        60.00,
        81.00,
        350.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        87
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Acrílico sobre lienzo'),
        'Bunbury II',
        'bunbury-ii',
        2024,
        NULL,
        NULL,
        60.00,
        81.00,
        350.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        88
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Acrílico sobre lienzo'),
        'Cyrus',
        'cyrus',
        2024,
        NULL,
        NULL,
        60.00,
        81.00,
        350.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        89
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Acrílico sobre lienzo'),
        'Freddie II',
        'freddie-ii',
        2024,
        NULL,
        NULL,
        60.00,
        81.00,
        350.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        90
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Acrílico sobre lienzo'),
        'Bowie III',
        'bowie-iii',
        2023,
        NULL,
        NULL,
        80.00,
        80.00,
        350.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        91
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Acrílico sobre lienzo'),
        'Bunbury III',
        'bunbury-iii',
        2023,
        NULL,
        NULL,
        60.00,
        60.00,
        NULL,
        'SOLD'::artwork_status,
        FALSE,
        TRUE,
        92
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Acrílico sobre lienzo'),
        'Jim Morrison',
        'jim-morrison',
        2023,
        NULL,
        NULL,
        60.00,
        60.00,
        250.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        93
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Acrílico sobre lienzo'),
        'lennon II',
        'lennon-ii',
        2023,
        NULL,
        NULL,
        60.00,
        60.00,
        250.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        94
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Acrílico sobre lienzo'),
        'Maddona II',
        'maddona-ii',
        2023,
        NULL,
        NULL,
        100.00,
        100.00,
        450.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        95
    ),
    (
        (SELECT id FROM collection WHERE slug = 'leyendas-de-la-musica'),
        (SELECT id FROM technique WHERE name = 'Acrílico sobre lienzo'),
        'Malikian',
        'malikian',
        2023,
        NULL,
        NULL,
        60.00,
        60.00,
        350.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        96
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Tauste en fiestas',
        'tauste-en-fiestas',
        2022,
        NULL,
        NULL,
        100.00,
        73.00,
        NULL,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        97
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Casa Perico',
        'casa-perico',
        2022,
        NULL,
        NULL,
        90.00,
        65.00,
        600.00,
        'SOLD'::artwork_status,
        FALSE,
        TRUE,
        98
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'The Big Apple',
        'the-big-apple',
        2026,
        NULL,
        NULL,
        120.00,
        60.00,
        NULL,
        'PRIVATE_COLLECTION'::artwork_status,
        FALSE,
        TRUE,
        99
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Entrando al Tercer Milenio',
        'entrando-al-tercer-milenio',
        2025,
        NULL,
        NULL,
        60.00,
        81.00,
        NULL,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        100
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'La naturaleza siempre vence',
        'la-naturaleza-siempre-vence',
        2026,
        NULL,
        NULL,
        100.00,
        100.00,
        NULL,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        101
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Imagine',
        'imagine',
        2020,
        NULL,
        NULL,
        65.00,
        81.00,
        600.00,
        'SOLD'::artwork_status,
        FALSE,
        TRUE,
        102
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Incomunicacion',
        'incomunicacion',
        2022,
        NULL,
        NULL,
        120.00,
        40.00,
        640.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        103
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Sanatorio de Agramonte',
        'sanatorio-de-agramonte',
        2021,
        NULL,
        NULL,
        60.00,
        60.00,
        350.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        104
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'David II',
        'david-ii',
        2025,
        NULL,
        NULL,
        60.00,
        81.00,
        NULL,
        'PRIVATE_COLLECTION'::artwork_status,
        FALSE,
        TRUE,
        105
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Happy',
        'happy',
        NULL,
        NULL,
        NULL,
        73.00,
        100.00,
        NULL,
        'PRIVATE_COLLECTION'::artwork_status,
        FALSE,
        TRUE,
        106
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Aprendiz de payaso',
        'aprendiz-de-payaso',
        2024,
        NULL,
        NULL,
        80.00,
        80.00,
        NULL,
        'PRIVATE_COLLECTION'::artwork_status,
        FALSE,
        TRUE,
        107
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Pastel sobre papel'),
        'Homenaje a Luis Royo I',
        'homenaje-a-luis-royo-i',
        2018,
        NULL,
        NULL,
        30.00,
        40.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        108
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Pastel sobre papel'),
        'Homenaje a Luis Royo II',
        'homenaje-a-luis-royo-ii',
        2018,
        NULL,
        NULL,
        30.00,
        40.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        109
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Pastel sobre papel'),
        'Homenaje a Luis Royo III',
        'homenaje-a-luis-royo-iii',
        2018,
        NULL,
        NULL,
        30.00,
        40.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        110
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Homenaje a Goyo Dominguez',
        'homenaje-a-goyo-dominguez',
        2019,
        NULL,
        NULL,
        60.00,
        81.00,
        450.00,
        'SOLD'::artwork_status,
        FALSE,
        TRUE,
        111
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Juan Pareja',
        'juan-pareja',
        2019,
        NULL,
        NULL,
        60.00,
        81.00,
        200.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        112
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Tuareg',
        'tuareg',
        2020,
        NULL,
        NULL,
        60.00,
        81.00,
        600.00,
        'SOLD'::artwork_status,
        FALSE,
        TRUE,
        113
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Iñaki, il giovane vigile di Ponte Vecchio',
        'inaki-il-giovane-vigile-di-ponte-vecchio',
        2021,
        NULL,
        NULL,
        60.00,
        81.00,
        600.00,
        'SOLD'::artwork_status,
        FALSE,
        TRUE,
        114
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Ana',
        'ana',
        2025,
        NULL,
        NULL,
        60.00,
        81.00,
        NULL,
        'PRIVATE_COLLECTION'::artwork_status,
        FALSE,
        TRUE,
        115
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Acrílico sobre lienzo'),
        'Autorretrato',
        'autorretrato',
        2025,
        NULL,
        NULL,
        60.00,
        81.00,
        NULL,
        'PRIVATE_COLLECTION'::artwork_status,
        FALSE,
        TRUE,
        116
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Isabelle II',
        'isabelle-ii',
        2025,
        NULL,
        NULL,
        100.00,
        100.00,
        800.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        117
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Sad Man',
        'sad-man',
        2025,
        NULL,
        NULL,
        100.00,
        100.00,
        800.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        118
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Tengo sed',
        'tengo-sed',
        2025,
        NULL,
        NULL,
        60.00,
        81.00,
        650.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        119
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Yaya Vito',
        'yaya-vito',
        2025,
        NULL,
        NULL,
        60.00,
        81.00,
        NULL,
        'PRIVATE_COLLECTION'::artwork_status,
        FALSE,
        TRUE,
        120
    ),
    (
        (SELECT id FROM collection WHERE slug = 'retratos'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Testigo mudo',
        'testigo-mudo',
        2026,
        NULL,
        NULL,
        60.00,
        81.00,
        NULL,
        'PRIVATE_COLLECTION'::artwork_status,
        FALSE,
        TRUE,
        121
    ),
    (
        (SELECT id FROM collection WHERE slug = 'paisaje-urbano'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Torre Utebo',
        'torre-utebo',
        2024,
        NULL,
        NULL,
        60.00,
        81.00,
        NULL,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        122
    ),
    (
        (SELECT id FROM collection WHERE slug = 'otras-obras'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Fondo marino',
        'fondo-marino',
        2021,
        NULL,
        NULL,
        80.00,
        180.00,
        800.00,
        'SOLD'::artwork_status,
        FALSE,
        TRUE,
        123
    ),
    (
        (SELECT id FROM collection WHERE slug = 'otras-obras'),
        (SELECT id FROM technique WHERE name = 'Óleo sobre lienzo'),
        'Estudio para la cabeza de Apolo',
        'estudio-para-la-cabeza-de-apolo',
        2022,
        NULL,
        NULL,
        60.00,
        81.00,
        560.00,
        'AVAILABLE'::artwork_status,
        FALSE,
        TRUE,
        124
    )
    ON CONFLICT (slug) DO NOTHING;
