-- =========================================================
-- Seed manual: exposiciones de Vicente Ruiz
-- Fuente: exposiciones_vicente_ruiz_colectivas_una_columna.html
--
-- sort_order se mantiene por tipo:
--   INDIVIDUAL: orden de aparición en el HTML
--   COLLECTIVE: orden cronológico descendente del HTML
--
-- Las colectivas no incluyen fechas exactas en la fuente:
-- start_date y end_date se dejan NULL y se usa year.
-- image_url se deja NULL hasta cargar los carteles como assets.
-- =========================================================

INSERT INTO exhibition (
    title,
    slug,
    type,
    description,
    start_date,
    end_date,
    year,
    location_name,
    location_address,
    image_url,
    is_current,
    sort_order
)
VALUES
(
    'Pinceladas de vida',
    'pinceladas-de-vida',
    'INDIVIDUAL'::exhibition_type,
    'Una selección de pinturas al óleo que recorre las dos líneas que atraviesan buena parte de la obra de Vicente Ruiz: el retrato y el paisaje urbano. La muestra reúne escenas, personajes y espacios marcados por el paso del tiempo, buscando detener la mirada en aquello que suele quedar fuera del centro de atención.',
    '2024-04-11'::date,
    '2024-05-10'::date,
    2024,
    'Centro Cultural Mariano Mesonada · Museo Orús',
    'Utebo, Zaragoza',
    NULL,
    FALSE,
    1
),
(
    'Retratos que dan la nota',
    'retratos-que-dan-la-nota',
    'INDIVIDUAL'::exhibition_type,
    'Una exposición centrada en el retrato de figuras vinculadas a la música. El gesto, la actitud escénica y la memoria colectiva asociada a cada intérprete son el punto de partida para una serie de obras que busca trasladar al lienzo parte de la energía y la personalidad de quienes han dejado huella sobre un escenario.',
    '2022-11-07'::date,
    '2022-11-30'::date,
    2022,
    'Casa de la Cámara',
    'Tauste, Zaragoza',
    NULL,
    FALSE,
    2
),
(
    'Inquietudes',
    'inquietudes',
    'INDIVIDUAL'::exhibition_type,
    'Retrato y paisaje urbano conviven en una muestra atravesada por la preocupación por la mirada humana, los espacios abandonados y las historias que permanecen en sus márgenes. La exposición incorpora además una serie de retratos a carboncillo inspirados en la obra del fotógrafo Lee Jeffries, invitando al espectador a ir más allá de la experiencia visual y reflexionar sobre distintas formas de abandono.',
    '2022-10-07'::date,
    '2022-10-30'::date,
    2022,
    'Casa de la Cámara',
    'Tauste, Zaragoza',
    NULL,
    FALSE,
    3
),
(
    'Miradas y visiones',
    'miradas-y-visiones',
    'INDIVIDUAL'::exhibition_type,
    'La mirada funciona como hilo conductor de una exposición que alterna retratos con paisaje urbano. Los ojos aparecen como vehículos de emociones difíciles de ocultar, mientras los espacios abandonados se presentan como visiones de lugares que tuvieron vida en un pasado reciente y que hoy permanecen como imágenes suspendidas de lo efímero.',
    '2022-03-02'::date,
    '2022-04-18'::date,
    2022,
    'Red de Centros Cívicos de Zaragoza',
    'Zaragoza',
    NULL,
    FALSE,
    4
),
(
    'Leyendas de la música',
    'leyendas-de-la-musica',
    'INDIVIDUAL'::exhibition_type,
    'Un tributo pictórico a grandes nombres de la música popular. La muestra reúne retratos al óleo de intérpretes reconocibles por varias generaciones y propone un recorrido visual por voces, gestos e iconografías que forman parte de la memoria musical contemporánea.',
    '2020-03-14'::date,
    '2020-03-15'::date,
    2020,
    'Centro Cívico Delicias',
    'Avda. de Navarra, 54 · Zaragoza',
    NULL,
    FALSE,
    5
),
(
    'Ventanas del alma',
    'ventanas-del-alma',
    'INDIVIDUAL'::exhibition_type,
    'Colección de dibujos de temática social concebida como homenaje al trabajo del fotógrafo británico Lee Jeffries. Primeros planos, cicatrices y miradas se convierten en una vía para acercarse a personas anónimas marcadas por la marginación y el desamparo. Las obras, de 40 × 40 cm, fueron realizadas con carboncillo y lápiz Conté sobre papel de acuarela.',
    '2020-03-02'::date,
    '2020-03-29'::date,
    2020,
    'Sala de Exposiciones · Centro Cívico Delicias',
    'Avda. de Navarra, 54 · Zaragoza',
    NULL,
    FALSE,
    6
),
(
    'Harmony of Vision',
    'harmony-of-vision',
    'COLLECTIVE'::exhibition_type,
    'Exposición internacional itinerante. Obra: “Nostalgy”.',
    NULL,
    NULL,
    2026,
    'Hsinchu 241 Art Space, Taipei (Taiwan) e Illuminati Fine Art Gallery, Hong Kong (China)',
    NULL,
    NULL,
    FALSE,
    1
),
(
    'Arte por un Tubo',
    'arte-por-un-tubo-2026',
    'COLLECTIVE'::exhibition_type,
    'Obras: “Alma del Ebro” y “Pilar”.',
    NULL,
    NULL,
    2026,
    'Zaragoza',
    NULL,
    NULL,
    FALSE,
    2
),
(
    'XXXIII Ruta del Arte',
    'xxxiii-ruta-del-arte',
    'COLLECTIVE'::exhibition_type,
    'Obra: “Entrando al Tercer Milenio”.',
    NULL,
    NULL,
    2025,
    'Colectivo APMI · Zaragoza',
    NULL,
    NULL,
    FALSE,
    3
),
(
    '7th Annual WFA Agency Exhibition',
    '7th-annual-wfa-agency-exhibition',
    'COLLECTIVE'::exhibition_type,
    'Obra: “Little Italy”.',
    NULL,
    NULL,
    2024,
    'Nueva York',
    NULL,
    NULL,
    FALSE,
    4
),
(
    'NYC Gallery Openings',
    'nyc-gallery-openings',
    'COLLECTIVE'::exhibition_type,
    'Obras: “Lovely waste” y “Nostalgy”.',
    NULL,
    NULL,
    2023,
    'Nueva York',
    NULL,
    NULL,
    FALSE,
    5
),
(
    'Arte por un Tubo',
    'arte-por-un-tubo-2023',
    'COLLECTIVE'::exhibition_type,
    'Obras: “Dulce Mirada” y “Otro día”.',
    NULL,
    NULL,
    2023,
    'Zaragoza',
    NULL,
    NULL,
    FALSE,
    6
),
(
    'Exposición de casas pasiegas',
    'exposicion-de-casas-pasiegas',
    'COLLECTIVE'::exhibition_type,
    'Obras: “Casas pasiegas I” y “Casas pasiegas II”.',
    NULL,
    NULL,
    2023,
    'Liérganes, Cantabria · Asociación Resbaladero de Ludana',
    NULL,
    NULL,
    FALSE,
    7
),
(
    'The MEAM Hall',
    'the-meam-hall-2023',
    'COLLECTIVE'::exhibition_type,
    'Obras: “After painting” y “Otro día”.',
    NULL,
    NULL,
    2023,
    'Museo Europeo de Arte Moderno · Barcelona',
    NULL,
    NULL,
    FALSE,
    8
),
(
    'The MEAM Hall',
    'the-meam-hall-2022',
    'COLLECTIVE'::exhibition_type,
    'Obras: “Nostalgia” y “La partida”.',
    NULL,
    NULL,
    2022,
    'Museo Europeo de Arte Moderno · Barcelona',
    NULL,
    NULL,
    FALSE,
    9
),
(
    'XXXIII Premio de Arte Santa Isabel de Aragón, Reina de Portugal',
    'xxxiii-premio-de-arte-santa-isabel-de-aragon-reina-de-portugal',
    'COLLECTIVE'::exhibition_type,
    'Obra: “Vigilando el abandono”.',
    NULL,
    NULL,
    2022,
    'Palacio de Sástago · Diputación Provincial de Zaragoza',
    NULL,
    NULL,
    FALSE,
    10
),
(
    'VI Salón de Primavera de Pintura Realista',
    'vi-salon-de-primavera-de-pintura-realista',
    'COLLECTIVE'::exhibition_type,
    'Obra: “Joven melómano”.',
    NULL,
    NULL,
    2022,
    'Sala Maruja Mallo · Madrid',
    NULL,
    NULL,
    FALSE,
    11
),
(
    'XXX Ruta del Arte',
    'xxx-ruta-del-arte',
    'COLLECTIVE'::exhibition_type,
    'Obra: “Estudio para la cabeza de Apolo”.',
    NULL,
    NULL,
    2022,
    'Colectivo APMI · Zaragoza',
    NULL,
    NULL,
    FALSE,
    12
),
(
    'XXIV Certamen Nacional de Pintura “Ciudad de Calahorra”',
    'xxiv-certamen-nacional-de-pintura-ciudad-de-calahorra',
    'COLLECTIVE'::exhibition_type,
    'Obra: “Cara oculta de Piazza San Marco”.',
    NULL,
    NULL,
    2020,
    'Calahorra',
    NULL,
    NULL,
    FALSE,
    13
),
(
    'Museum MundoArti',
    'museum-mundoarti',
    'COLLECTIVE'::exhibition_type,
    'Obra: “Desde el cuarto creciente”.',
    NULL,
    NULL,
    2020,
    'Exposición virtual',
    NULL,
    NULL,
    FALSE,
    14
)
ON CONFLICT (slug) DO NOTHING;
